### PR TITLE
Add Flag to Reset the DB on Shutdown.

### PR DESCRIPTION
**Pull request by favalos**
Pull request to add the flag discussed in #97.

I had to add a reset flag to every DB configuration and change the Reset implementation.

Other approach could be doing the implementation on the Shutdown method, but that would imply to add a new `Resetable() bool` method to the subsystem interface.

Please let me know your comments.

### CODE REVIEW

**Comment by dfarr** [comment]
Thank you so much for the contribution @favalos!

I have one (hopefully) small change to ask.

The shutdown function on the api/aio interfaces are used as a signal to _begin_ a graceful shutdown. The aio method is currently unused, but we do use it on the api side. When this signal is received we stop taking new requests but continue to process any sqes/cqes already in the system until all are complete. As such we can't reset the database via the shutdown function as we still need to write to the database after this function has been called.

You can see the shutdown process [here](https://github.com/resonatehq/resonate/blob/main/cmd/serve/serve.go#L148-L170).

1. shutdown signal received (happens in a go routine and calls api.shutdown+aio.shutdown via `system.Shutdown`)
2. `system.Loop` will return once all outstanding sqes/cqes are complete
3. `api.Stop()` called
4. `aio.Stop()` called (internally calls Stop for all subsystems)

I recommend moving the call to Reset (if the flag is true) the Stop function, this is when we can safely reset.

**Comment by favalos** [comment]
Hi @dfarr,

Thanks for the detailed explanation, I did the changes accordingly.

Let me know if that looks fine.

**Comment by guergabo** [comment]
Thank you @favalos for contributing to resonate !!!

**Review by dfarr — APPROVED** [review]
Looks great! Thank you @favalos

**Comment by dfarr** [comment]
Closes #97

**Pull request merged**
